### ISSUE TITLE
When using, the app is crash APP_SCOUT_WARNING

### ISSUE THREAD

**Issue by abedputra** [wongpiwat/flutter-trust-location#20]
Test on: POCO F5
Flutter: 3.7.12
Version:   trust_location: ^2.0.13

The app freezes for about 30 seconds, then the error below appears. After 30 seconds the app can run again.

Error:
```
W/MIUIScout App(30447): Enter APP_SCOUT_WARNING State
W/MIUIScout App(30447):  (Current message: duration=2504ms seq=429 h=com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler w=1)
W/MIUIScout App(30447): Event:APP_SCOUT_WARNING Thread:main backtrace:
W/MIUIScout App(30447):     at jdk.internal.misc.Unsafe.park(Native Method)
W/MIUIScout App(30447):     at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
W/MIUIScout App(30447):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
W/MIUIScout App(30447):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
W/MIUIScout App(30447):     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
W/MIUIScout App(30447):     at com.google.android.gms.internal.location.zzau.getLastLocation(com.google.android.gms:play-services-location@@21.0.1:12)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant.checkInitialLocation(LocationAssistant.java:494)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant.access$600(LocationAssistant.java:57)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:730)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:722)
W/MIUIScout App(30447):     at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.1.0:6)
W/MIUIScout App(30447):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(30447):     at android.os.Looper.loopOnce(Looper.java:211)
W/MIUIScout App(30447):     at android.os.Looper.loop(Looper.java:300)
W/MIUIScout App(30447):     at android.app.ActivityThread.main(ActivityThread.java:8310)
W/MIUIScout App(30447):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(30447):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/MIUIScout App(30447):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
I/withfingerprin(30447): Thread[6,tid=30472,WaitingInMainSignalCatcherLoop,Thread*=0xb40000792743b000,peer=0x138419a0,"Signal Catcher"]: reacting to signal 3
I/withfingerprin(30447):
I/withfingerprin(30447): Wrote stack traces to tombstones

W/MIUIScout App(30447): Enter APP_SCOUT_HANG state
W/MIUIScout App(30447):  (Current message: duration=5006ms seq=429 h=com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler w=1)
W/MIUIScout App(30447): Event:APP_SCOUT_HANG Thread:main backtrace:
W/MIUIScout App(30447):     at jdk.internal.misc.Unsafe.park(Native Method)
W/MIUIScout App(30447):     at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
W/MIUIScout App(30447):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
W/MIUIScout App(30447):     at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
W/MIUIScout App(30447):     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
W/MIUIScout App(30447):     at com.google.android.gms.internal.location.zzau.getLastLocation(com.google.android.gms:play-services-location@@21.0.1:12)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant.checkInitialLocation(LocationAssistant.java:494)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant.access$600(LocationAssistant.java:57)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:730)
W/MIUIScout App(30447):     at com.wongpiwat.trust_location.LocationAssistant$8.onResult(LocationAssistant.java:722)
W/MIUIScout App(30447):     at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@18.1.0:6)
W/MIUIScout App(30447):     at android.os.Handler.dispatchMessage(Handler.java:106)
W/MIUIScout App(30447):     at android.os.Looper.loopOnce(Looper.java:211)
W/MIUIScout App(30447):     at android.os.Looper.loop(Looper.java:300)
W/MIUIScout App(30447):     at android.app.ActivityThread.main(ActivityThread.java:8310)
W/MIUIScout App(30447):     at java.lang.reflect.Method.invoke(Native Method)
W/MIUIScout App(30447):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
W/MIUIScout App(30447):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
```

**Comment by madmouse17** [comment]
My problem is same, help please

My device Redmi 9pro
